// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SmartFactory.Data;

#nullable disable

namespace SmartFactory.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("SmartFactory.Data.Entities.MachineEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("MachineId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Machines");

                    b.HasData(
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111111"),
                            IsActive = true,
                            MachineId = "press-01",
                            Name = "Press 01",
                            Type = "Press"
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222222"),
                            IsActive = true,
                            MachineId = "cnc-01",
                            Name = "CNC 01",
                            Type = "CNC"
                        },
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-333333333333"),
                            IsActive = true,
                            MachineId = "conveyor-01",
                            Name = "Conveyor 01",
                            Type = "Conveyor"
                        });
                });

            modelBuilder.Entity("SmartFactory.Data.Entities.MachineTelemetryEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("AlarmActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsRunning")
                        .HasColumnType("boolean");

                    b.Property<string>("MachineId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("SavedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("Timestamp")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable((string)null);

                    b.UseTpcMappingStrategy();
                });

            modelBuilder.Entity("SmartFactory.Data.Entities.CncTelemetryEntity", b =>
                {
                    b.HasBaseType("SmartFactory.Data.Entities.MachineTelemetryEntity");

                    b.Property<double>("FeedRate")
                        .HasColumnType("double precision");

                    b.Property<double>("SpindleRpm")
                        .HasColumnType("double precision");

                    b.Property<double>("ToolWear")
                        .HasColumnType("double precision");

                    b.ToTable("CncTelemetries");
                });

            modelBuilder.Entity("SmartFactory.Data.Entities.ConveyorTelemetryEntity", b =>
                {
                    b.HasBaseType("SmartFactory.Data.Entities.MachineTelemetryEntity");

                    b.Property<double>("BeltSpeed")
                        .HasColumnType("double precision");

                    b.Property<int>("ItemsPerMinute")
                        .HasColumnType("integer");

                    b.Property<double>("MotorCurrent")
                        .HasColumnType("double precision");

                    b.ToTable("ConveyorTelemetries");
                });

            modelBuilder.Entity("SmartFactory.Data.Entities.HydraulicPressTelemetryEntity", b =>
                {
                    b.HasBaseType("SmartFactory.Data.Entities.MachineTelemetryEntity");

                    b.Property<int>("CyclesPerHour")
                        .HasColumnType("integer");

                    b.Property<double>("HydraulicPressure")
                        .HasColumnType("double precision");

                    b.Property<double>("RamPosition")
                        .HasColumnType("double precision");

                    b.ToTable("HydraulicPressTelemetries");
                });
#pragma warning restore 612, 618
        }
    }
}
